const data = {
    products: [
      {
      name: 'Nike short sleeve',
      slug: 'nike-short-sleeve',
      category: 'Shirts',
      image: '/images/ss1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
      },
      {
        name: 'Nike Button shirt',
        slug: 'nike-button-shirt',
        category: 'Shirts',
        image: '/images/ls1.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality shirt',
      },
      {
        name: 'Nike Best slacks',
        slug: 'nike-best-slacks',
        category: 'Pants',
        image: '/images/pt1.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality pants',
      },{
        name: 'Nike Commuter Pants',
        slug: 'nike-commuter-pants',
        category: 'Pants',
        image: '/images/pt2.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality sportswear',
      },
    ],
  }

  export default data;
